---
- name: make www group
  group: name={{ www_user }} gid=2000 state=present

- name: make webmaster group
  group: name={{ webmaster_user }} gid=2001 state=present

- name: make www user
  user: name={{ www_user }} group={{ www_user }} uid=2000

- name: make webmaster user
  user: name={{ webmaster_user }} group={{ webmaster_user }} uid=2001

- name: chmod /home/webmaster
  file:
    path: /home/{{ webmaster_user }}
    mode: 0755

- name: install apache
  yum:
    state: installed
    name:
      - httpd
      - mod_ssl

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: open http port
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: open https port
  firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: true

