# 基本部分のインストール
- name: EPEL/Remi
  yum:
    name:
      - epel-release
      - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  become: true

- name: general tool
  yum:
    name:
      - gcc
      - zip
      - unzip
      - vim
      - wget
      - yum-utils
      - git
      - firewalld
      - bzip2
  become: true
